[package]
edition = "2024"
name = "mc"
resolver = "2"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

# [lints.clippy]
# pedantic = "warn"
# nursery = "warn"

[dependencies]
anyhow = "1.0.86"
bytemuck = { version = "1.16.1", features = ["derive"] }
egui = "0.33.3"
egui-wgpu = "0.33.3"
egui-winit = {version = "0.33.3", default-features = false }
enum-map = "2.7.3"
env_logger = "0.11.3"
glam = { version = "0.30.8", features = ["bytemuck"] }
image = "0.25.1"
itertools = "0.14.0"
lazy_static = "1.5.0"
log = "0.4.21"
noise = "0.9.0"
pollster = "0.3.0"
rand_pcg = "0.9.0"
rayon = "1.11.0"
ron = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }
smallvec = "1.15.1"
thiserror = "2.0.17"
web-time = "1.1.0"
wgpu = "27.0.1"
winit = "0.30.12"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
futures = "0.3.31"
js-sys = "0.3.85"
wasm-bindgen = "0.2.108"
wasm-bindgen-futures = "0.4.58"
web-sys = { version = "0.3.85", features = [
    "Document",
    "Element",
    "Window",
    "Worker",
    'Headers',
    'MessageEvent',
    'Request',
    'RequestInit',
    'RequestMode',
    'Response',
    'WorkerOptions',
    'WorkerType',
] }

[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
dwarf-debug-info = true

[dev-dependencies]
googletest = "0.14.0"
